<?php

function podcast_view_menu(){
      $items['path-to-ajax/%/%'] = array(
            'access arguments' => array('access content'),
            'page callback' => 'podcast_view_ajax_callback',
            'page arguments' => array(1,2),
            'type' => MENU_CALLBACK,
      );
      return $items;
}

function podcast_view_ajax_callback($js, $node_id){
      $node = node_load($node_id);

      if($js === 'nojs'){
        drupal_goto('node/' . $node->id);
      }

      $build = node_view($node);
      $html = render($build);

      $commands = array();
      $commands[] = ajax_command_html('#podcast-view-ajax-wrapper', $html);

      print ajax_render($commands);
      exit;
}
